config/routes.rb
StockTrader::Application.routes.draw do

  get 'testdispatch' => 'stocks#dispatchtest'
  get 'newtest' => 'stocks#newtest'

  get 'ajaxtest' => 'stocks#ajaxtest'
  get 'deleteer' => 'stocks#deleteer'
  
  get 'uploadCSV' => 'stocks#uploadCSV'
  post 'upload' => 'stocks#upload'
  get 'deleter' => 'stocks#deleter'

  get 'ajaxtest2' => 'stocks#ajaxtest2'

  get 'ajaxtestpage' => 'stocks#ajaxtestpage'
  resources :stocks do
    resources :trades
  end

end

app/models/stock.rb
class Stock < ActiveRecord::Base
	has_many :trades
	validates_uniqueness_of :symbol
	accepts_nested_attributes_for :trades
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]

  # GET /stocks
  # GET /stocks.json
  def index
    @stocks = Stock.all
    @totalrevenue = Trade.where(:action => "SELL").sum('shares*price')
    @totalcost = Trade.where(:action => "BUY").sum('shares*price')
    @overall = @totalrevenue - @totalcost

  end

  def dispatchtest 
    render :inline => 'holyshit'
  end

  def deleter
    respond_to do |format|
      format.html 
      format.js   
    end
  end
  def deleteer
    @action = params[:selected]
    if @action == "sell"
      @stocksDropDown = ""
      @sellStocks = Stock.where("shares>0")
      @sellStocks.each do |stock| 
        symbol = stock.symbol.to_s
        @stocksDropDown = @stocksDropDown + '<option value="' + symbol + '">' + symbol + '</option>'
      end      
      @stocksDropDown = '<select>' + @stocksDropDown + '</select>'
    else 
      @stocksDropDown = ""
    end


    respond_to do |format|
      format.html 
      format.js   
    end
  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
    @trades = @stock.trades
    @totalrevenue = @stock.trades.where(:action => "SELL").sum('shares*price')
    @totalcost = @stock.trades.where(:action => "BUY").sum('shares*price')
    @overall = @totalrevenue - @totalcost
    
    #Trade.where(:action => "BUY", :stock_id => 11).sum(shares*price)
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end


  def ajaxtestpage    
  end

  # GET /stocks/new
  def newtest
    @sellStocks = Trade.where("action=?", "SELL")
    @stock = Stock.new
  end

  def ajaxtest
    action = params[:selected]
    if action == "sell"
      @stocksDropDown = ""
      @sellStocks = Stock.where("shares>0")
      @sellStocks.each do |stock| 
        symbol = stock.symbol.to_s
        @stocksDropDown = @stocksDropDown + '<option value="' + symbol + '">' + symbol + '</option>'
      end      
      @stocksDropDown = '<select>' + @stocksDropDown + '</select>'
      render :text => @stocksDropDown
    else 
      render :text => "nothing"
    end
  end


  def ajaxNumShares
    @symbol = params[:symbol]
    @myStock = Stock.where("symbol=" + @symbol)
    render :text => @myStock.shares
  end


  def ajaxtest2
    @action = params[:selected]
    if @action == "sell"
      @stocksDropDown = ""
      @sellStocks = Stock.where("shares>0")
      @sellStocks.each do |stock| 
        symbol = stock.symbol.to_s
        @stocksDropDown = @stocksDropDown + '<option value="' + symbol + '">' + symbol + '</option>'
      end      
      @stocksDropDown = '<select>' + @stocksDropDown + '</select>'
    else 
      @stocksDropDown = ""
    end



    respond_to do |format|
      format.html 
      format.js   
    end
  end


  def uplaodCSV
  end

  def upload
    require 'csv'
    uploaded_io = params[:picture]
    uploaded_filepath = Rails.root.join('public', 'uploads', uploaded_io.original_filename)
    #File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
    File.open(uploaded_filepath, 'wb') do |file|    
      file.write(uploaded_io.read)
    end



    @people = []
    #CSV.foreach(File.path(Rails.root.join('public', 'uploads', uploaded_io.original_filename))) do |col|
    #CSV.foreach(File.path('stocks.csv')) do |col|    
    CSV.foreach(File.path(uploaded_filepath)) do |col|    

      #@people =  @people + col[0].to_s + "<br>"
      #@people << col[0].to_s + " " + col[1].to_s
      old_stock = Stock.find_by symbol: col[2]
      if old_stock
        new_trade = old_stock.trades.new(action: col[1], status: "ACTIVE", price: col[4], shares: col[3], date_posted: DateTime.strptime(col[0], '%m/%d/%y'))
        new_trade.save

        #new_trade = old_stock.trades.new
        #new_trade.action = col[1]
        #(action: col[1].to_s, status: "ACTIVE".to_s, price: 111, shares: col[3].to_s)

        #@people = @people = old_stock.symbol
      else
        new_stock = Stock.new(symbol: col[2])
        new_stock.save
        #new_stock.trades.new()
        new_trade = new_stock.trades.new(action: col[1], status: "ACTIVE", price: col[4], shares: col[3], date_posted: DateTime.strptime(col[0], '%m/%d/%y'))
        new_trade.save
      end

      #find Stock ID by using symbol
      #if it doesn't exist then insert new Stock row 
      #else use stock ID 
      #create new trade off of stock == @stock.TRade.create()
    end

  end

  # POST /stocks
  # POST /stocks.json
  def create
    params[:stock][:cost] = params[:trade][:price]
    params[:stock][:shares] = params[:trade][:shares]

    @stock = Stock.new(stock_params)
    #@trade = @stock.trades.build(trade_params)
    @trade = @stock.trades.new(trade_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: 'Stock was successfully created.' }
        format.json { render action: 'show', status: :created, location: @stock }
      else
        format.html { render action: 'new' }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1
  # PATCH/PUT /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_params
      #params.require(:stock).permit(:symbol, :cost, :shares)
      params.require(:stock).permit(:symbol, :cost, :shares)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trade_params
      params.require(:trade).permit(:action, :status, :price, :shares, :date_posted, :stock_id)
    end
end

app/helpers/stocks_helper.rb
module StocksHelper
 require 'net/http'

  def calculate_profitloss(marketprice, cost)
    if cost == 0
      return 0
    end
  	difference = marketprice.to_f - cost
  	percentage = (difference/cost) * 100
    percentage = percentage.round(2)
    difference = difference.round(2).to_s
  	difference + " (" + percentage .to_s + "%)"
  end

  def stock_price(symbol)
	  #symbol = params[:symbol]
	  url = URI::parse "http://download.finance.yahoo.com/d/quotes.csv?s=#{symbol}&f=s0n0b0a0t1p0o0x0"
	  req = Net::HTTP::get(url).gsub /"/, ''
	  elems = req.split(",")
	  elems[2]
	  #{}"hi"

	  #req.split(",")
	#  respond_to do |format|
	 #   format.json { render :json => req.split(",") and return}
	 # end
    
    #gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    #size = options[:size]
    #gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    #image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/stocks/_form.html.erb
<%= form_for(@stock) do |f| %>
  <% if @stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
      <% @stock.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :symbol %><br>
    <%= f.text_field :symbol %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.text_field :cost %>
  </div>
  <div class="field">
    <%= f.label :shares %><br>
    <%= f.number_field :shares %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stocks/_trades.html.erb
<h3>Listing trades</h3>

<table class="table">
  <thead>
    <tr>
      <th>Action</th>
      <th>Status</th>
      <th>Price</th>
      <th>Shares</th>
      <th>Date posted</th>
      <th>Total Amount</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @trades.each do |trade| %>
      <tr>
        <td><%= trade.action.upcase %></td>
        <td><%= trade.status %></td>
        <td><%= number_to_currency trade.price %></td>
        <td><%= trade.shares %></td>
        <td><%= trade.date_posted.to_date %></td>
        <td><%= number_to_currency(trade.price * trade.shares) %></td>                
        <td><%= link_to 'Show', [@stock, trade] %></td>
        <td><%= link_to 'Edit', [:edit, @stock, trade] %></td>
        <td><%= link_to 'Destroy', [@stock, trade], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trade', [:new, @stock, :trade] %>

app/views/stocks/ajaxtest2.js.erb
alert("hi");




alert("<%= @action %>");

if("<%= @action %>" == "sell") {
  $("#buyfield").hide();
  $("#sellfield").show();
  //$("#updatefield").html('<select>');
  $("#updatefield").html('<%= @stocksDropDown.html_safe %>');

  $("#numshares").html('<%= @numShares %>');
}
if("<%= @action %>" == "buy")  {
  $("#sellfield").hide();
  $("#buyfield").show();

}


alert("hi");

app/views/stocks/ajaxtestpage.html.erb
<%= link_to "Preview Widget", :action => 'dispatchtest' , :id => @stock, :remote => true %>
<a href="deleter" class="delete_post" data-confirm="Are you sure?" data-remote="true" rel="nofollow">Destroy</a>
	  <div class="field">
	   
	  </div>
    <div class="field">
      <select id="action">
        <option value="buy">Buy</option>
        <option value="sell">Sell</opion>
        </select>
    </div>

<div id="updatefield"></div>

<div id="sellfield">hi</div>
<div id="buyfield">hi2</div>
<script type="text/javascript">
$(function($) {

    $("#action").change(function() {
 $.get("<%= url_for :action => 'deleteer' %>", { selected: this.value}, null, "script");
    	   //$.post(that.attr('rel'), {id: that.val()}, null, "script");


//var jqxhr = $.get( "<%= url_for :action => 'ajaxtest' %>", { selected: this.value});

/*
.done(function() {
alert( "second success" );
})
.fail(function() {
alert( "error" );
})
.always(function() {
alert( "finished" );
});
*/
// Perform other work here ...
// Set another completion function for the request above
//jqxhr.always(function(data) {
//alert( "done : " + data);
//alert(this.value);
//$("#updatefield").html(data);

//});

//})
    });


});
</script>

app/views/stocks/deleteer.js.erb
alert("hi");
$("#updatefield").html("<%= @stocksDropDown %>");

alert("<%= @action %>");

if("<%= @action %>" == "sell") {
  $("#buyfield").hide();
  $("#sellfield").show();

}
if("<%= @action %>" == "buy")  {
  $("#sellfield").hide();
  $("#buyfield").show();

}


alert("hi");

app/views/stocks/deleter.js.erb
alert("hi");
$("#updatefield").html(<%= @stocksDropDown %>);

if(@action == "sell") {
  $("#buyfield").hide();
  $("#sellfield").show();

}
if(@action == "buy")  {
  $("#sellfield").hide();
  $("#buyfield").show();

}

app/views/stocks/dispatchtest.html.erb
test

app/views/stocks/edit.html.erb
<h1>Editing stock</h1>

<%= render 'form' %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<h1>Listing stocks</h1>


<p>Total Profit: <%= number_to_currency @overall %></p>
<table class="table">
  <thead>
    <tr>
      <th>Symbol</th>
      <th>Market Price</th>
      <th>Cost</th>
      <th>Shares</th>
      <th>Current Value</th>
      <th>Cost Basis</th>          
      <th>Profit/Loss</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @stocks.each do |stock| %>
    <% cost_basis = stock.shares * stock.cost %>
    <% marketprice = stock_price(stock.symbol) %>
    <% marketprice = 0 unless marketprice.to_f > 0 %>  
    <% if marketprice.to_f > 0
        cur_basis = marketprice.to_f * stock.shares 
      else 
        cur_basis = 0
      end   
    %>    
      <tr>
        <td><%= stock.symbol.upcase %></td>
        <td><%= number_to_currency marketprice %></td>        
        <td><%= number_to_currency stock.cost %></td>
        <td><%= stock.shares %></td>
        <td><%= number_to_currency cur_basis %></td>
        <td><%= number_to_currency cost_basis %></td>          
        <td>
          <% if(stock.cost) %>
            <%= calculate_profitloss(marketprice, stock.cost) %>
          <% end %>
          </td>
        <td><%= link_to 'Show', stock %></td>
        <td><%= link_to 'Edit', edit_stock_path(stock) %></td>
        <td><%= link_to 'Destroy', stock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stock', new_stock_path %>

app/views/stocks/new.html.erb
<h1>New stock</h1>

<%= render 'form' %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/newtest.html.erb
<h1>New stock</h1>
    <% @sellStocks.each do |stock| %>
      <%= stock.price %><br />
    <% end %>
<%= form_for(@stock) do |f| %>
  <% if @stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
      <% @stock.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


        <% if false %>
        <div class="field">
          <%= f.label :cost %><br>
          <%= f.text_field :cost %>
        </div>
        <div class="field">
          <%= f.label :shares %><br>
          <%= f.number_field :shares %>
        </div>
      <% end %>

  <%= fields_for :trade do |trade_fields| %>
	  <div class="field">
	    <%= trade_fields.label :action %><br>	    
	  </div>
    <div class="field">
      <select id="action">
        <option value="buy">Buy</option>
        <option value="sell">Sell</opion>
        </select>
    </div>


  <div class="field" id="buyfield">
    <%= f.label :symbol %><br>
    <%= f.text_field :symbol %>    
  </div>
  <div class="field" id="sellfield" style="display:none;">
    <%= f.label :symbol %><br>    
    <span id="updatefield">tt</span>
  </div>

	  <div class="field">
	    <%= trade_fields.label :status %><br>
	    <%= trade_fields.text_field :status %>
	  </div>
	  <div class="field">
	    <%= trade_fields.label :price %><br>
	    <%= trade_fields.text_field :price %>
	  </div>
	  <div class="field">
	    <%= trade_fields.label :shares %><br>
	    <%= trade_fields.number_field :shares %> <span id="numshares"></span>
	  </div>
	  <div class="field">
	    <%= trade_fields.label :date_posted %><br>
	    <%= trade_fields.date_select :date_posted %>
	  </div>
  <% end %>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', stocks_path %>



<script type="text/javascript">
$(function($) {
    $("#action").change(function() {
      //  $.ajax({url: '<%= url_for :action => 'ajaxtest' %>',
//        data: 'selected=' + this.value,
  //      dataType: 'script', success})
// Assign handlers immediately after making the request,
// and remember the jqxhr object for this request

/*
if(this.value == "sell") {
  $("#buyfield").hide();
  $("#sellfield").show();

}
if(this.value == "buy")  {
  $("#sellfield").hide();
  $("#buyfield").show();

}
*/
 $.get("<%= url_for :action => 'ajaxtest2' %>", { selected: this.value}, null, "script");

//var jqxhr = $.get( "<%= url_for :action => 'ajaxtest' %>", { selected: this.value});

/*
.done(function() {
alert( "second success" );
})
.fail(function() {
alert( "error" );
})
.always(function() {
alert( "finished" );
});
*/
// Perform other work here ...
// Set another completion function for the request above
//jqxhr.always(function(data) {
//alert( "done : " + data);
//alert(this.value);
//$("#updatefield").html(data);

//});

//})
    });


});
</script>

app/views/stocks/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  Overall Profit/Loss: <%= number_to_currency @overall %>
</p>
<p>
  Percentage? <%= @overall/@totalcost unless @totalcost == 0 %>
</p>
<p>
  <strong>Symbol:</strong>
  <%= @stock.symbol %>
</p>

<p>
  <strong>Market Price:</strong>
  <%= number_to_currency stock_price(@stock.symbol) %>
</p>

<p>
  <strong>Cost:</strong>
  <%= number_to_currency @stock.cost %>
</p>

<p>
  <strong>Shares:</strong>
  <%= @stock.shares %>
</p>

<p>
    		<%= render 'trades' %>

	</p>

<%= link_to 'Edit', edit_stock_path(@stock) %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/upload.html.erb
<h1>Uploaded Stocks CSV</h1>
<br>
<%= @people.to_s.html_safe %>
<%= link_to 'New Stock', new_stock_path %>

app/views/stocks/uploadCSV.html.erb
<h1>Upload Stocks CSV</h1>

<%= form_tag({action: :upload}, multipart: true) do %>
  <%= file_field_tag 'picture' %>
    <%= submit_tag %>

<% end %>
<br>

<%= link_to 'New Stock', new_stock_path %>