config/routes.rb
StockTrader::Application.routes.draw do

  get 'testdispatch' => 'stocks#dispatchtest'
  get 'newtest' => 'stocks#newtest'

  get 'ajaxtest' => 'stocks#ajaxtest'
  get 'deleteer' => 'stocks#deleteer'
  
  get 'uploadCSV' => 'stocks#uploadCSV'
  post 'upload' => 'stocks#upload'
  get 'deleter' => 'stocks#deleter'

  get 'ajaxtest2' => 'stocks#ajaxtest2'

  get 'ajaxtestpage' => 'stocks#ajaxtestpage'
  resources :stocks do
    resources :trades
  end

end

app/models/trade.rb
class Trade < ActiveRecord::Base
	belongs_to :stock, dependent: :destroy
end

app/controllers/trades_controller.rb
class TradesController < ApplicationController
  before_action :set_trade, only: [:show, :edit, :update, :destroy]
  before_filter :get_stock



  def get_stock
    @stock = Stock.find(params[:stock_id])
  end

  # GET /trades
  # GET /trades.json
  def index
    #@trades = Trade.all
    @trades =  Stock.find(params[:stock_id]).trades.all

  end

  # GET /trades/1
  # GET /trades/1.json
  def show
  end

  # GET /trades/new
  def new
    @trade = Trade.new
  end

  # GET /trades/1/edit
  def edit
  end

  # POST /trades
  # POST /trades.json
  def create
    @trade = @stock.trades.new(trade_params)
    #@trade = Trade.new(trade_params)

    respond_to do |format|
      if @trade.save
        format.html { redirect_to [@stock, @trade], notice: 'Trade was successfully created.' }
        format.json { render action: 'show', status: :created, location: @trade }
      else
        format.html { render action: 'new' }
        format.json { render json: @trade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trades/1
  # PATCH/PUT /trades/1.json
  def update
    respond_to do |format|
      if @trade.update(trade_params)
        format.html { redirect_to @trade, notice: 'Trade was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @trade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trades/1
  # DELETE /trades/1.json
  def destroy
    @trade.destroy
    respond_to do |format|
      format.html { redirect_to trades_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trade
      @trade = Trade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trade_params
      params.require(:trade).permit(:action, :status, :price, :shares, :date_posted, :stock_id)
    end
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/views/trades/_form.html.erb
<%= form_for([@stock, @trade]) do |f| %>
  <% if @trade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trade.errors.count, "error") %> prohibited this trade from being saved:</h2>

      <ul>
      <% @trade.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :action %><br>
    <%= f.text_field :action %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :shares %><br>
    <%= f.number_field :shares %>
  </div>
  <div class="field">
    <%= f.label :date_posted %><br>
    <%= f.date_select :date_posted %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trades/edit.html.erb
<h1>Editing trade</h1>

<%= render 'form' %>

<%= link_to 'Show', @trade %> |
<%= link_to 'Back', trades_path %>

app/views/trades/index.html.erb
<h1>Listing trades</h1>

<table class="table">
  <thead>
    <tr>
      <th>Action</th>
      <th>Status</th>
      <th>Price</th>
      <th>Shares</th>  
      <th>Date posted</th>
      <th>Total Amount</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @trades.each do |trade| %>
      <tr>
        <td><%= trade.action.upcase %></td>
        <td><%= trade.status %></td>
        <td><%= number_to_currency trade.price %></td>
        <td><%= trade.shares %></td>
        <td><%= trade.date_posted.to_date %></td>
        <td><%= number_to_currency(trade.price * trade.shares) %></td>        
        <td><%= link_to 'Show', [@stock, trade] %></td>
        <td><%= link_to 'Edit', [:edit, @stock, trade] %></td>
        <td><%= link_to 'Destroy', [@stock, trade], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Ne1w Trade', [:new, @stock, :trade] %>

app/views/trades/new.html.erb
<h1>New trade</h1>

<%= render 'form' %>

<%= link_to 'Back', [@stock, :trades] %>

app/views/trades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Action:</strong>
  <%= @trade.action %>
</p>

<p>
  <strong>Status:</strong>
  <%= @trade.status %>
</p>

<p>
  <strong>Price:</strong>
  <%= @trade.price %>
</p>

<p>
  <strong>Shares:</strong>
  <%= @trade.shares %>
</p>

<p>
  <strong>Date posted:</strong>
  <%= @trade.date_posted.to_date %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @trade.stock_id %>
</p>

<%= link_to 'Edit', [:edit, @stock, @trade] %> |
<%= link_to 'Back', [@stock] %>